on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
    - cron: '0 0 * * 6'
  
name: Semgrep
jobs:
  buildmavenDepTree:
        runs-on: ubuntu-latest
        container:
          image: semgrep/semgrep
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots package
        - name: Build Dependency Tree
          run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt
        - name: Upload Dependency Tree Artifact
          uses: actions/upload-artifact@v3
          with:
            name: mavendeptree
            path: maven_dep_tree.txt
            
  semgrep:
    name: Scan
    needs: buildmavenDepTree
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from previous job
      uses: actions/download-artifact@v3
      with:
        name: mavendeptree
    - run: semgrep ci  --sarif-output=semgrep-results.sarif

    # upload the results for the CodeQL GitHub app to annotate the code
    - name: Save SARIF results as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-scan-results
        path: semgrep-results.sarif

    # Upload SARIF file generated in previous step
    - name: Upload SARIF result to the GitHub Security Dashboard
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep-results.sarif
     
