on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 16 2 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci  --sarif-output=semgrep-results.sarif

    # upload the results for the CodeQL GitHub app to annotate the code
    - name: Save SARIF results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-scan-results
        path: semgrep-results.sarif

    # Upload SARIF file generated in previous step
    - name: Upload SARIF result to the GitHub Security Dashboard
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep-results.sarif
      if: always()
